[project]
name = "ty-django-issue"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-lsp-server>=1.13.1",
    "ty>=0.0.1a23",
]

[tool.uv.workspace]
members = [
    "webserver",
]
